// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKQwNofBY2yeGWK0nP44tiEziYLfuWu4M',
    appId: '1:871331499650:android:76e28f6d8bc89bdd3e2e9b',
    messagingSenderId: '871331499650',
    projectId: 'internconnect-909f5',
    storageBucket: 'internconnect-909f5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBluTHIs0dF_wI-Anu43PXDRzfjfc95iQY',
    appId: '1:871331499650:ios:d9d613e8a10aeb7d3e2e9b',
    messagingSenderId: '871331499650',
    projectId: 'internconnect-909f5',
    storageBucket: 'internconnect-909f5.firebasestorage.app',
    iosBundleId: 'com.example.internConnect',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9SZepEX7xIsHh_MbJJQ-KPjRybMVGvd8',
    appId: '1:871331499650:web:3306ff24f389c1ef3e2e9b',
    messagingSenderId: '871331499650',
    projectId: 'internconnect-909f5',
    authDomain: 'internconnect-909f5.firebaseapp.com',
    storageBucket: 'internconnect-909f5.firebasestorage.app',
  );
}
